
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: cd my-app && npm install
    command: cd my-app && npm run start